name: Node CI

on:
  push:
    branches: 
      - master
      - gh-pages 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm run deploy
      run: |
        export GIT_USER=secret.GIT_USER
        git config credential.helper '!f() { sleep 1; echo "username=${secret.GIT_USER}"; echo "password=${secret.GIT_PASSWORD}"; }; f'
        npm install
        npm run deploy
      env:
        CI: true
